schemaVersion = 1
commandMode = "COMMAND_CUSTOM"
command = "changepassword"

[[children]]
child = "key"
type = "argument"
argumentType = "minecraft:word"

  [[children.actions]]
  command = "trigger change_password set {{key}}"
  commandType = "CLIENT"